### PR TITLE
Retry commit: Fail if lmbench test fails, and make it easy to enable/disable tests

### PR DESCRIPTION
**Pull request by bpjain**
Recommitting changes for review.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
Looks good, modulo some minor polishing (see my comments).

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-:-LXyVVxo6_d-oG3f7uAh:bqyb7w6)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @bpjain)

*[a discussion](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXy9OBF9N0MNdEA_QVH:-LXy9OBF9N0MNdEA_QVI:bo8022u) (no related file):*
Could you please fix email address in the commits so that GitHub recognize it? Alternatively, you can just add this email to you GitHub account.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyCJIi0fy3GkMb3zva:-LXyCJIj8rHophHPIIL2:be1qlje) (no related file):*
> Retry commit 
Please remove this from commit message or add `:` after it, right now it's a bit confusing.

---
___
*[lmbench-regression, line 118 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyL4CKEBxIOwYUMp9y:-LXyL4CL3PAyUHYfcYoS:becgp27) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L118)):*
> ```
> fi
> 
> cp hello /tmp/hello
> ```

I think this may break if running in parallel with other instance.
Also, what's the purpose of this command? Is this file used anywhere?
___
*[lmbench-regression, line 147 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyV3O80O4fWiEmqAGZ:-LXyV3O80O4fWiEmqAG_:bp4s1to) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L147)):*
> ```
> 
> function wr_bw {
> 	for i in $(eval echo "{1..$N_RUNS}")
> ```

Is there any reason to iterate this way? Why not just use `seq 1 $N_RUNS` ?
If there's no reason then please also refactor other loops to use the simpler version.
___
*[lmbench-regression, line 171 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyNHGj6pSkpaDctiF8:-LXyNHGj6pSkpaDctiF9:bkdzu6q) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L171)):*
> ```
> 	for i in $(eval echo "{1..$N_RUNS}")
> 	do	run lat_tcp 127.0.0.1
> 		sleep 1
> ```

Could you please move `run lat_tcp [...]` to the next line? Now it doesn't align with `sleep 1`. Same for all other places.
If you don't want to add unnecessary additional line you can move `do` to the previous line this way:
```Bash
for i in $(eval echo "{1..$N_RUNS}"); do
    run lat_tcp 127.0.0.1
    sleep1
done
```
___
*[lmbench-regression, line 179 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyUpUP95gAcWr7uqEx:-LXyUpUQ9MrK1vb6Rh3S:b-uka5xw) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/7e84b3f8ab3607ff74948e7e1c0ef2771babe5d6/lmbench-regression#L179)):*
> ```
> for i in $(eval echo "{1..$N_RUNS}")
> ```
___
*[lmbench-regression, line 213 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyPMCT-VfdJvz4BY44:-LXyPMCT-VfdJvz4BY45:b-hvhx33) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L213)):*
> ```
> 
> declare -a tests=(\
> 			"lat_syscall null" \
> ```

`\`s are not required here (and even if they would, line comments break them)
___
*[lmbench-regression, line 230 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyTbt293FCwcV6rSK9:-LXyTbt293FCwcV6rSKA:bkovg03) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L230)):*
> ```
> ## DEP 12/9/17: Temporarily remove vfork from the unit tests
> #			"lat_proc vfork" \
> 		       "lat_proc exec" \
> ```

Please fix indentation here
___
*[lmbench-regression, line 257 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyUNvw2ExC2GgzFz04:-LXyUNvw2ExC2GgzFz05:bxyble8) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L257)):*
> ```
> for i in `seq 0 $((${#tests[@]}-1))`
> do
> echo "Running ${tests[$i]}"
> ```

Please add indentation here and move `do` to the previous line. Same for all other not indented loops.
___
*[lmbench-regression, line 268 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyUYvr2WKKgXKeGKy7:-LXyUYvr2WKKgXKeGKy8:b-rv6m6e) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L268)):*
> ```
> done
> 
> rm -f /tmp/hello
> ```

ditto (why is this required?)

**Review by bpjain — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7)* status: 0 of 1 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXy9OBF9N0MNdEA_QVH:-LXymGqz9xXA6wlgBc6s:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you please fix email address in the commits so that GitHub recognize it? Alternatively, you can just add this email to you GitHub account.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyCJIi0fy3GkMb3zva:-LXyqZ-j44UgkuxDsBrG:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Retry commit 
Please remove this from commit message or add `:` after it, right now it's a bit confusing.
</blockquote></details>

Done.

---
___
*[lmbench-regression, line 118 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyL4CKEBxIOwYUMp9y:-LXyh6e-6_Fq-_FleeOj:b-l0phl5) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this may break if running in parallel with other instance.
Also, what's the purpose of this command? Is this file used anywhere?
</blockquote></details>

lat_proc testcase for fork, exec, etc. uses this.
___
*[lmbench-regression, line 147 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyV3O80O4fWiEmqAGZ:-LXyhWnd0y-Eb-Pqj4Vn:b-fsh7gi) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L147)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is there any reason to iterate this way? Why not just use `seq 1 $N_RUNS` ?
If there's no reason then please also refactor other loops to use the simpler version.
</blockquote></details>

This is how it was done before. I just moved the code around. Changed in the new commit.
___
*[lmbench-regression, line 171 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyNHGj6pSkpaDctiF8:-LXyjo465iHm60FXOKG2:b-896fix) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L171)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you please move `run lat_tcp [...]` to the next line? Now it doesn't align with `sleep 1`. Same for all other places.
If you don't want to add unnecessary additional line you can move `do` to the previous line this way:
```Bash
for i in $(eval echo "{1..$N_RUNS}"); do
    run lat_tcp 127.0.0.1
    sleep1
done
```
</blockquote></details>

Done.
___
*[lmbench-regression, line 179 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyUpUP95gAcWr7uqEx:-LXyjkld6nLvbYVDsG1d:b-896fix) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/7e84b3f8ab3607ff74948e7e1c0ef2771babe5d6/lmbench-regression#L179)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> for i in $(eval echo "{1..$N_RUNS}")
> ```

</blockquote></details>

Done.
___
*[lmbench-regression, line 213 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyPMCT-VfdJvz4BY44:-LXyjy-774jk7zYJ5q_R:b-896fix) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L213)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`\`s are not required here (and even if they would, line comments break them)
</blockquote></details>

Done.
___
*[lmbench-regression, line 230 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyTbt293FCwcV6rSK9:-LXyltyOEwbWzJxYGcsL:b-896fix) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L230)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix indentation here
</blockquote></details>

Done.
___
*[lmbench-regression, line 257 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyUNvw2ExC2GgzFz04:-LXylvGM12x42HVL2mqa:b-896fix) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L257)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add indentation here and move `do` to the previous line. Same for all other not indented loops.
</blockquote></details>

Done.
___
*[lmbench-regression, line 268 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyUYvr2WKKgXKeGKy7:-LXylx1xDCEVDaINcgRD:b-q64pkt) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (why is this required?)
</blockquote></details>

See above.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @bpjain)

___
*[lmbench-regression, line 118 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyL4CKEBxIOwYUMp9y:-LXyue_T8391S0Sig0nG:bxvmydf) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L118)):*
<details><summary><i>Previously, bpjain wrote…</i></summary><blockquote>

lat_proc testcase for fork, exec, etc. uses this.
</blockquote></details>

Won't this break when running a few instances of tests on the same machine? (e.g. a Jenkins node testing a few builds in parallel)
___
*[lmbench-regression, line 147 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyV3O80O4fWiEmqAGZ:-LXyuwpI1jLTW2Gm_7nP:b-ucfknh) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L147)):*
<details><summary><i>Previously, bpjain wrote…</i></summary><blockquote>

This is how it was done before. I just moved the code around. Changed in the new commit.
</blockquote></details>

Thanks!

**Comment by bpjain** [comment]
___
*[lmbench-regression, line 118 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyL4CKEBxIOwYUMp9y:-LXyyF4WCHUyVkxWSrZ5:b-yklg5r) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Won't this break when running a few instances of tests on the same machine? (e.g. a Jenkins node testing a few builds in parallel)
</blockquote></details>

I could change the script so that the hello binary is not deleted at the end, and the script copies the hello binary only if it doesn't already exist. That should take care of that. What do you think?

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @bpjain)

___
*[lmbench-regression, line 118 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyL4CKEBxIOwYUMp9y:-LXyzWYJEOA4c4MChOVH:b9tg99l) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L118)):*
<details><summary><i>Previously, bpjain wrote…</i></summary><blockquote>

I could change the script so that the hello binary is not deleted at the end, and the script copies the hello binary only if it doesn't already exist. That should take care of that. What do you think?
</blockquote></details>

I'm still not too happy with such solution. Why those tests require a file in a fixed, absolute location? Why a file in CWD isn't enough? If they really require an absolute path I'd prefer to parametrize them and pass a path created by `mktemp` or just absolute path to CWD+filename (in such case I'd prefer to do that in a separate PR).

**Comment by bpjain** [comment]
___
*[lmbench-regression, line 118 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyL4CKEBxIOwYUMp9y:-LXz3O032TmWRpYxkNK3:b-kaw8n0) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm still not too happy with such solution. Why those tests require a file in a fixed, absolute location? Why a file in CWD isn't enough? If they really require an absolute path I'd prefer to parametrize them and pass a path created by `mktemp` or just absolute path to CWD+filename (in such case I'd prefer to do that in a separate PR).
</blockquote></details>

There is no way to pass the executable path as a parameter. What you suggest will need changes to be made to the lmbench lat_proc testcase file src/lat_proc.c. Let me know how you want to proceed?

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @bpjain)

___
*[lmbench-regression, line 118 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyL4CKEBxIOwYUMp9y:-LXzc3ht0C6SkLlIS5aM:b5pjcv5) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L118)):*
<details><summary><i>Previously, bpjain wrote…</i></summary><blockquote>

There is no way to pass the executable path as a parameter. What you suggest will need changes to be made to the lmbench lat_proc testcase file src/lat_proc.c. Let me know how you want to proceed?
</blockquote></details>

I meant, we could just add additional commandline argument to `lat_proc` binary with the path. Right now it uses a hardcoded `#define`, changing this to `argv[2]` should be quite simple.

For now, let's just remove that `rm`, it's the most dangerous part. I'll create an issue about fixing this problem, as I read this script now, it seems that similar issues are widespread here.

**Comment by bpjain** [comment]
___
*[lmbench-regression, line 118 at r1](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LXyL4CKEBxIOwYUMp9y:-LY2TVPs2HFJJfPcj3Zb:bs7wumx) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/a5a1889e65f3f26783a8a9ee10702c23a959f127/lmbench-regression#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I meant, we could just add additional commandline argument to `lat_proc` binary with the path. Right now it uses a hardcoded `#define`, changing this to `argv[2]` should be quite simple.

For now, let's just remove that `rm`, it's the most dangerous part. I'll create an issue about fixing this problem, as I read this script now, it seems that similar issues are widespread here.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by donporter — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @bpjain)

___
*[lmbench-regression, line 247 at r3](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LZ0e1Ca5jraduu3DCHX:-LZ0e1Ca5jraduu3DCHY:b-dgvdmq) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/821340ce0527be02af633df4710139488ceb50af/lmbench-regression#L247)):*
> ```
> ## DEP 12/9/17: Temporarily remove vfork from the unit tests
> #			"lat_proc vfork"
> 			"lat_proc exec"
> ```

Per PR #6, please drop this test too.

**Comment by bpjain** [comment]
___
*[lmbench-regression, line 247 at r3](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7#-LZ0e1Ca5jraduu3DCHX:-LZ5uPGJ7pKECZDr6_a2:b-896fix) ([raw file](https://github.com/oscarlab/lmbench-2.5/blob/821340ce0527be02af633df4710139488ceb50af/lmbench-regression#L247)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Per PR #6, please drop this test too.
</blockquote></details>

Done.

**Review by donporter — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/lmbench-2.5/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by donporter** [comment]
Please resolve this conflict with master, and squash into one commit, and then we are going to be ready to merge this.  Thanks!

**Pull request merged**
